id: b1e0346625e341e0adf3e665505efa97
initial_creation_type: ocr
source_metadata:
  volumes:
    04cbcb23f79d45aea6fb6a573a1481bf:
      base_file: v038.txt
      image_group_id: I1PD95883
      title: ''
      total_pages: 1044
      volume_number: 38
